// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include character\clientscripts\c_usa_seal6;

main()
{
    character\clientscripts\c_usa_seal6::main();
    self._aitype = "Ally_SEAL_Blackout_Assault_Base";
}

precache( ai_index )
{
    character\clientscripts\c_usa_seal6::precache();
    usefootsteptable( ai_index, "default_ai" );
    setdemolockonvalues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
