// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include character\clientscripts\c_usa_cia_combat_harper_cin;

main()
{
    character\clientscripts\c_usa_cia_combat_harper_cin::main();
    self._aitype = "Hero_Harper_Blackout";
}

precache( ai_index )
{
    character\clientscripts\c_usa_cia_combat_harper_cin::precache();
    usefootsteptable( ai_index, "default_ai" );
    setdemolockonvalues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
